spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: null
  mvc:
    view:
      prefix: /view/
      suffix: .jsp

server:
  port: 9090
  
  
phonebook: 
  messages:
     contactSaveSucc: Contact Saved Successfully
     contactSaveFail: Failed to save contact
     contactUpdateSucc: Contact Updadted Successfully
     contactDeleteSucc: Contact Deleted Successfully
     contactDeleteFail: Contact Failed to Delete  